// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
    // Ajoute les autres plateformes si nécessaire.
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAqvU9Pa96rTYon1YfobiAARMylB7tetVU",
      authDomain: "game-project-55bad.firebaseapp.com",
      projectId: "game-project-55bad",
      storageBucket: "game-project-55bad.appspot.com",
      messagingSenderId: "523395239586",
      appId: "1:523395239586:web:652b6db2ecadb744a911fb"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtn6D4lo5bcl1_MXk9FfKdplpVOI7WLR4',
    appId: '1:523395239586:android:f314988afccfcf45a911fb',
    messagingSenderId: '523395239586',
    projectId: 'game-project-55bad',
    storageBucket: 'game-project-55bad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANh-aN1B4Bv5zZMHU49aTUZxAoFs4rsyk',
    appId: '1:523395239586:ios:17cbc6105c328395a911fb',
    messagingSenderId: '523395239586',
    projectId: 'game-project-55bad',
    storageBucket: 'game-project-55bad.appspot.com',
    iosBundleId: 'com.example.naningana',
  );

}